### ISSUE TITLE
Can remove all "java" ( awt / io/ ImageIO) dependencies  Full Kotlin ?

### ISSUE THREAD

**Issue by CMingTseng** [PhenixFine/steganography-and-cryptography#1]
Dear Sir

thx  your Academy and demo

but this demo use 

 java.awt.Color
 java.awt.image.BufferedImage
  java.io.File
  javax.imageio.ImageIO
  
  how let demo use full kotlin ?
  
  THX

**Comment by PhenixFine** [comment]
I had to give up on being a programmer. There may be Kotlin libraries now for image manipulation but there wasn't back when I wrote the code ( or at least I couldn't find anything at the time ). There's nothing wrong with having java dependencies, unless you're trying to code in their Multiplatform, which I thought was awful at the time, but may have improved.
